#开发环境
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc\:oracle\:thin\:@10.1.1.181\:1521\:ora11
    username: hstd
    password: hstd
    max-active: 50
    max-idle: 5
    min-idle: 0
  