package com.hstd.exchange.entity.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PJ_ASSOCIATOR
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class AssociatorKey {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PJ_ASSOCIATOR.ID
     *
     * @mbggenerated
     */
    private long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PJ_ASSOCIATOR.ID
     *
     * @return the value of PJ_ASSOCIATOR.ID
     *
     * @mbggenerated
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PJ_ASSOCIATOR.ID
     *
     * @param id the value for PJ_ASSOCIATOR.ID
     *
     * @mbggenerated
     */
    public void setId(long id) {
        this.id = id;
    }
}