package com.hstd.exchange.entity.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AssociatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public AssociatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(long value1, long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(long value1, long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAcctNoIsNull() {
            addCriterion("ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andAcctNoIsNotNull() {
            addCriterion("ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAcctNoEqualTo(String value) {
            addCriterion("ACCT_NO =", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotEqualTo(String value) {
            addCriterion("ACCT_NO <>", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoGreaterThan(String value) {
            addCriterion("ACCT_NO >", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACCT_NO >=", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLessThan(String value) {
            addCriterion("ACCT_NO <", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLessThanOrEqualTo(String value) {
            addCriterion("ACCT_NO <=", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoLike(String value) {
            addCriterion("ACCT_NO like", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotLike(String value) {
            addCriterion("ACCT_NO not like", value, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoIn(List<String> values) {
            addCriterion("ACCT_NO in", values, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotIn(List<String> values) {
            addCriterion("ACCT_NO not in", values, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoBetween(String value1, String value2) {
            addCriterion("ACCT_NO between", value1, value2, "acctNo");
            return (Criteria) this;
        }

        public Criteria andAcctNoNotBetween(String value1, String value2) {
            addCriterion("ACCT_NO not between", value1, value2, "acctNo");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("MOBILE_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("MOBILE_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("MOBILE_PHONE =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("MOBILE_PHONE <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("MOBILE_PHONE >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("MOBILE_PHONE <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("MOBILE_PHONE like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("MOBILE_PHONE not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("MOBILE_PHONE in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("MOBILE_PHONE not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andCustTypeIsNull() {
            addCriterion("CUST_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCustTypeIsNotNull() {
            addCriterion("CUST_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCustTypeEqualTo(String value) {
            addCriterion("CUST_TYPE =", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotEqualTo(String value) {
            addCriterion("CUST_TYPE <>", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeGreaterThan(String value) {
            addCriterion("CUST_TYPE >", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CUST_TYPE >=", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLessThan(String value) {
            addCriterion("CUST_TYPE <", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLessThanOrEqualTo(String value) {
            addCriterion("CUST_TYPE <=", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLike(String value) {
            addCriterion("CUST_TYPE like", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotLike(String value) {
            addCriterion("CUST_TYPE not like", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeIn(List<String> values) {
            addCriterion("CUST_TYPE in", values, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotIn(List<String> values) {
            addCriterion("CUST_TYPE not in", values, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeBetween(String value1, String value2) {
            addCriterion("CUST_TYPE between", value1, value2, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotBetween(String value1, String value2) {
            addCriterion("CUST_TYPE not between", value1, value2, "custType");
            return (Criteria) this;
        }

        public Criteria andLinkmanIsNull() {
            addCriterion("LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andLinkmanIsNotNull() {
            addCriterion("LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andLinkmanEqualTo(String value) {
            addCriterion("LINKMAN =", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotEqualTo(String value) {
            addCriterion("LINKMAN <>", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanGreaterThan(String value) {
            addCriterion("LINKMAN >", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("LINKMAN >=", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLessThan(String value) {
            addCriterion("LINKMAN <", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLessThanOrEqualTo(String value) {
            addCriterion("LINKMAN <=", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanLike(String value) {
            addCriterion("LINKMAN like", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotLike(String value) {
            addCriterion("LINKMAN not like", value, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanIn(List<String> values) {
            addCriterion("LINKMAN in", values, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotIn(List<String> values) {
            addCriterion("LINKMAN not in", values, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanBetween(String value1, String value2) {
            addCriterion("LINKMAN between", value1, value2, "linkman");
            return (Criteria) this;
        }

        public Criteria andLinkmanNotBetween(String value1, String value2) {
            addCriterion("LINKMAN not between", value1, value2, "linkman");
            return (Criteria) this;
        }

        public Criteria andMbphoneIsNull() {
            addCriterion("MBPHONE is null");
            return (Criteria) this;
        }

        public Criteria andMbphoneIsNotNull() {
            addCriterion("MBPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMbphoneEqualTo(String value) {
            addCriterion("MBPHONE =", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneNotEqualTo(String value) {
            addCriterion("MBPHONE <>", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneGreaterThan(String value) {
            addCriterion("MBPHONE >", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneGreaterThanOrEqualTo(String value) {
            addCriterion("MBPHONE >=", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneLessThan(String value) {
            addCriterion("MBPHONE <", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneLessThanOrEqualTo(String value) {
            addCriterion("MBPHONE <=", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneLike(String value) {
            addCriterion("MBPHONE like", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneNotLike(String value) {
            addCriterion("MBPHONE not like", value, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneIn(List<String> values) {
            addCriterion("MBPHONE in", values, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneNotIn(List<String> values) {
            addCriterion("MBPHONE not in", values, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneBetween(String value1, String value2) {
            addCriterion("MBPHONE between", value1, value2, "mbphone");
            return (Criteria) this;
        }

        public Criteria andMbphoneNotBetween(String value1, String value2) {
            addCriterion("MBPHONE not between", value1, value2, "mbphone");
            return (Criteria) this;
        }

        public Criteria andConEmailIsNull() {
            addCriterion("CON_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andConEmailIsNotNull() {
            addCriterion("CON_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andConEmailEqualTo(String value) {
            addCriterion("CON_EMAIL =", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailNotEqualTo(String value) {
            addCriterion("CON_EMAIL <>", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailGreaterThan(String value) {
            addCriterion("CON_EMAIL >", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailGreaterThanOrEqualTo(String value) {
            addCriterion("CON_EMAIL >=", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailLessThan(String value) {
            addCriterion("CON_EMAIL <", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailLessThanOrEqualTo(String value) {
            addCriterion("CON_EMAIL <=", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailLike(String value) {
            addCriterion("CON_EMAIL like", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailNotLike(String value) {
            addCriterion("CON_EMAIL not like", value, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailIn(List<String> values) {
            addCriterion("CON_EMAIL in", values, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailNotIn(List<String> values) {
            addCriterion("CON_EMAIL not in", values, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailBetween(String value1, String value2) {
            addCriterion("CON_EMAIL between", value1, value2, "conEmail");
            return (Criteria) this;
        }

        public Criteria andConEmailNotBetween(String value1, String value2) {
            addCriterion("CON_EMAIL not between", value1, value2, "conEmail");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceIsNull() {
            addCriterion("ID_PHOTO_FACE is null");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceIsNotNull() {
            addCriterion("ID_PHOTO_FACE is not null");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceEqualTo(String value) {
            addCriterion("ID_PHOTO_FACE =", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceNotEqualTo(String value) {
            addCriterion("ID_PHOTO_FACE <>", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceGreaterThan(String value) {
            addCriterion("ID_PHOTO_FACE >", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceGreaterThanOrEqualTo(String value) {
            addCriterion("ID_PHOTO_FACE >=", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceLessThan(String value) {
            addCriterion("ID_PHOTO_FACE <", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceLessThanOrEqualTo(String value) {
            addCriterion("ID_PHOTO_FACE <=", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceLike(String value) {
            addCriterion("ID_PHOTO_FACE like", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceNotLike(String value) {
            addCriterion("ID_PHOTO_FACE not like", value, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceIn(List<String> values) {
            addCriterion("ID_PHOTO_FACE in", values, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceNotIn(List<String> values) {
            addCriterion("ID_PHOTO_FACE not in", values, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceBetween(String value1, String value2) {
            addCriterion("ID_PHOTO_FACE between", value1, value2, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoFaceNotBetween(String value1, String value2) {
            addCriterion("ID_PHOTO_FACE not between", value1, value2, "idPhotoFace");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackIsNull() {
            addCriterion("ID_PHOTO_BACK is null");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackIsNotNull() {
            addCriterion("ID_PHOTO_BACK is not null");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackEqualTo(String value) {
            addCriterion("ID_PHOTO_BACK =", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackNotEqualTo(String value) {
            addCriterion("ID_PHOTO_BACK <>", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackGreaterThan(String value) {
            addCriterion("ID_PHOTO_BACK >", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackGreaterThanOrEqualTo(String value) {
            addCriterion("ID_PHOTO_BACK >=", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackLessThan(String value) {
            addCriterion("ID_PHOTO_BACK <", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackLessThanOrEqualTo(String value) {
            addCriterion("ID_PHOTO_BACK <=", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackLike(String value) {
            addCriterion("ID_PHOTO_BACK like", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackNotLike(String value) {
            addCriterion("ID_PHOTO_BACK not like", value, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackIn(List<String> values) {
            addCriterion("ID_PHOTO_BACK in", values, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackNotIn(List<String> values) {
            addCriterion("ID_PHOTO_BACK not in", values, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackBetween(String value1, String value2) {
            addCriterion("ID_PHOTO_BACK between", value1, value2, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andIdPhotoBackNotBetween(String value1, String value2) {
            addCriterion("ID_PHOTO_BACK not between", value1, value2, "idPhotoBack");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNull() {
            addCriterion("PHOTO1 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNotNull() {
            addCriterion("PHOTO1 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto1EqualTo(String value) {
            addCriterion("PHOTO1 =", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotEqualTo(String value) {
            addCriterion("PHOTO1 <>", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThan(String value) {
            addCriterion("PHOTO1 >", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO1 >=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThan(String value) {
            addCriterion("PHOTO1 <", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThanOrEqualTo(String value) {
            addCriterion("PHOTO1 <=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Like(String value) {
            addCriterion("PHOTO1 like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotLike(String value) {
            addCriterion("PHOTO1 not like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1In(List<String> values) {
            addCriterion("PHOTO1 in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotIn(List<String> values) {
            addCriterion("PHOTO1 not in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Between(String value1, String value2) {
            addCriterion("PHOTO1 between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotBetween(String value1, String value2) {
            addCriterion("PHOTO1 not between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNull() {
            addCriterion("PHOTO2 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNotNull() {
            addCriterion("PHOTO2 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto2EqualTo(String value) {
            addCriterion("PHOTO2 =", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotEqualTo(String value) {
            addCriterion("PHOTO2 <>", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThan(String value) {
            addCriterion("PHOTO2 >", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO2 >=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThan(String value) {
            addCriterion("PHOTO2 <", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThanOrEqualTo(String value) {
            addCriterion("PHOTO2 <=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Like(String value) {
            addCriterion("PHOTO2 like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotLike(String value) {
            addCriterion("PHOTO2 not like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2In(List<String> values) {
            addCriterion("PHOTO2 in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotIn(List<String> values) {
            addCriterion("PHOTO2 not in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Between(String value1, String value2) {
            addCriterion("PHOTO2 between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotBetween(String value1, String value2) {
            addCriterion("PHOTO2 not between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto3IsNull() {
            addCriterion("PHOTO3 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto3IsNotNull() {
            addCriterion("PHOTO3 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto3EqualTo(String value) {
            addCriterion("PHOTO3 =", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotEqualTo(String value) {
            addCriterion("PHOTO3 <>", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3GreaterThan(String value) {
            addCriterion("PHOTO3 >", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3GreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO3 >=", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3LessThan(String value) {
            addCriterion("PHOTO3 <", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3LessThanOrEqualTo(String value) {
            addCriterion("PHOTO3 <=", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3Like(String value) {
            addCriterion("PHOTO3 like", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotLike(String value) {
            addCriterion("PHOTO3 not like", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3In(List<String> values) {
            addCriterion("PHOTO3 in", values, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotIn(List<String> values) {
            addCriterion("PHOTO3 not in", values, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3Between(String value1, String value2) {
            addCriterion("PHOTO3 between", value1, value2, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotBetween(String value1, String value2) {
            addCriterion("PHOTO3 not between", value1, value2, "photo3");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andApprovStatusIsNull() {
            addCriterion("APPROV_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andApprovStatusIsNotNull() {
            addCriterion("APPROV_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andApprovStatusEqualTo(String value) {
            addCriterion("APPROV_STATUS =", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusNotEqualTo(String value) {
            addCriterion("APPROV_STATUS <>", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusGreaterThan(String value) {
            addCriterion("APPROV_STATUS >", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusGreaterThanOrEqualTo(String value) {
            addCriterion("APPROV_STATUS >=", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusLessThan(String value) {
            addCriterion("APPROV_STATUS <", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusLessThanOrEqualTo(String value) {
            addCriterion("APPROV_STATUS <=", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusLike(String value) {
            addCriterion("APPROV_STATUS like", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusNotLike(String value) {
            addCriterion("APPROV_STATUS not like", value, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusIn(List<String> values) {
            addCriterion("APPROV_STATUS in", values, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusNotIn(List<String> values) {
            addCriterion("APPROV_STATUS not in", values, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusBetween(String value1, String value2) {
            addCriterion("APPROV_STATUS between", value1, value2, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andApprovStatusNotBetween(String value1, String value2) {
            addCriterion("APPROV_STATUS not between", value1, value2, "approvStatus");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoIsNull() {
            addCriterion("PHONE_APPROVNO is null");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoIsNotNull() {
            addCriterion("PHONE_APPROVNO is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoEqualTo(String value) {
            addCriterion("PHONE_APPROVNO =", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoNotEqualTo(String value) {
            addCriterion("PHONE_APPROVNO <>", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoGreaterThan(String value) {
            addCriterion("PHONE_APPROVNO >", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_APPROVNO >=", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoLessThan(String value) {
            addCriterion("PHONE_APPROVNO <", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoLessThanOrEqualTo(String value) {
            addCriterion("PHONE_APPROVNO <=", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoLike(String value) {
            addCriterion("PHONE_APPROVNO like", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoNotLike(String value) {
            addCriterion("PHONE_APPROVNO not like", value, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoIn(List<String> values) {
            addCriterion("PHONE_APPROVNO in", values, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoNotIn(List<String> values) {
            addCriterion("PHONE_APPROVNO not in", values, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoBetween(String value1, String value2) {
            addCriterion("PHONE_APPROVNO between", value1, value2, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPhoneApprovnoNotBetween(String value1, String value2) {
            addCriterion("PHONE_APPROVNO not between", value1, value2, "phoneApprovno");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedIsNull() {
            addCriterion("PASSWORD_CHANGED is null");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedIsNotNull() {
            addCriterion("PASSWORD_CHANGED is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedEqualTo(String value) {
            addCriterion("PASSWORD_CHANGED =", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedNotEqualTo(String value) {
            addCriterion("PASSWORD_CHANGED <>", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedGreaterThan(String value) {
            addCriterion("PASSWORD_CHANGED >", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD_CHANGED >=", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedLessThan(String value) {
            addCriterion("PASSWORD_CHANGED <", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD_CHANGED <=", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedLike(String value) {
            addCriterion("PASSWORD_CHANGED like", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedNotLike(String value) {
            addCriterion("PASSWORD_CHANGED not like", value, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedIn(List<String> values) {
            addCriterion("PASSWORD_CHANGED in", values, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedNotIn(List<String> values) {
            addCriterion("PASSWORD_CHANGED not in", values, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedBetween(String value1, String value2) {
            addCriterion("PASSWORD_CHANGED between", value1, value2, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andPasswordChangedNotBetween(String value1, String value2) {
            addCriterion("PASSWORD_CHANGED not between", value1, value2, "passwordChanged");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoIsNull() {
            addCriterion("EMAIL_APPROVNO is null");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoIsNotNull() {
            addCriterion("EMAIL_APPROVNO is not null");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoEqualTo(String value) {
            addCriterion("EMAIL_APPROVNO =", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoNotEqualTo(String value) {
            addCriterion("EMAIL_APPROVNO <>", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoGreaterThan(String value) {
            addCriterion("EMAIL_APPROVNO >", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_APPROVNO >=", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoLessThan(String value) {
            addCriterion("EMAIL_APPROVNO <", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_APPROVNO <=", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoLike(String value) {
            addCriterion("EMAIL_APPROVNO like", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoNotLike(String value) {
            addCriterion("EMAIL_APPROVNO not like", value, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoIn(List<String> values) {
            addCriterion("EMAIL_APPROVNO in", values, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoNotIn(List<String> values) {
            addCriterion("EMAIL_APPROVNO not in", values, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoBetween(String value1, String value2) {
            addCriterion("EMAIL_APPROVNO between", value1, value2, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andEmailApprovnoNotBetween(String value1, String value2) {
            addCriterion("EMAIL_APPROVNO not between", value1, value2, "emailApprovno");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNull() {
            addCriterion("REGISTER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNotNull() {
            addCriterion("REGISTER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateEqualTo(Date value) {
            addCriterion("REGISTER_DATE =", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotEqualTo(Date value) {
            addCriterion("REGISTER_DATE <>", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThan(Date value) {
            addCriterion("REGISTER_DATE >", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATE >=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThan(Date value) {
            addCriterion("REGISTER_DATE <", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThanOrEqualTo(Date value) {
            addCriterion("REGISTER_DATE <=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIn(List<Date> values) {
            addCriterion("REGISTER_DATE in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotIn(List<Date> values) {
            addCriterion("REGISTER_DATE not in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATE between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotBetween(Date value1, Date value2) {
            addCriterion("REGISTER_DATE not between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateIsNull() {
            addCriterion("APPROVE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andApproveDateIsNotNull() {
            addCriterion("APPROVE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andApproveDateEqualTo(Date value) {
            addCriterion("APPROVE_DATE =", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotEqualTo(Date value) {
            addCriterion("APPROVE_DATE <>", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateGreaterThan(Date value) {
            addCriterion("APPROVE_DATE >", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateGreaterThanOrEqualTo(Date value) {
            addCriterion("APPROVE_DATE >=", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLessThan(Date value) {
            addCriterion("APPROVE_DATE <", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateLessThanOrEqualTo(Date value) {
            addCriterion("APPROVE_DATE <=", value, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateIn(List<Date> values) {
            addCriterion("APPROVE_DATE in", values, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotIn(List<Date> values) {
            addCriterion("APPROVE_DATE not in", values, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateBetween(Date value1, Date value2) {
            addCriterion("APPROVE_DATE between", value1, value2, "approveDate");
            return (Criteria) this;
        }

        public Criteria andApproveDateNotBetween(Date value1, Date value2) {
            addCriterion("APPROVE_DATE not between", value1, value2, "approveDate");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIsNull() {
            addCriterion("TRADE_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIsNotNull() {
            addCriterion("TRADE_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andTradePasswordEqualTo(String value) {
            addCriterion("TRADE_PASSWORD =", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotEqualTo(String value) {
            addCriterion("TRADE_PASSWORD <>", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordGreaterThan(String value) {
            addCriterion("TRADE_PASSWORD >", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_PASSWORD >=", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLessThan(String value) {
            addCriterion("TRADE_PASSWORD <", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLessThanOrEqualTo(String value) {
            addCriterion("TRADE_PASSWORD <=", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordLike(String value) {
            addCriterion("TRADE_PASSWORD like", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotLike(String value) {
            addCriterion("TRADE_PASSWORD not like", value, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordIn(List<String> values) {
            addCriterion("TRADE_PASSWORD in", values, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotIn(List<String> values) {
            addCriterion("TRADE_PASSWORD not in", values, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordBetween(String value1, String value2) {
            addCriterion("TRADE_PASSWORD between", value1, value2, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andTradePasswordNotBetween(String value1, String value2) {
            addCriterion("TRADE_PASSWORD not between", value1, value2, "tradePassword");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("CLIENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("CLIENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("CLIENT_ID =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("CLIENT_ID <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("CLIENT_ID >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("CLIENT_ID >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("CLIENT_ID <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("CLIENT_ID <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("CLIENT_ID like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("CLIENT_ID not like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<String> values) {
            addCriterion("CLIENT_ID in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<String> values) {
            addCriterion("CLIENT_ID not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("CLIENT_ID between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("CLIENT_ID not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andPersonnameIsNull() {
            addCriterion("PERSONNAME is null");
            return (Criteria) this;
        }

        public Criteria andPersonnameIsNotNull() {
            addCriterion("PERSONNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPersonnameEqualTo(String value) {
            addCriterion("PERSONNAME =", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameNotEqualTo(String value) {
            addCriterion("PERSONNAME <>", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameGreaterThan(String value) {
            addCriterion("PERSONNAME >", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONNAME >=", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameLessThan(String value) {
            addCriterion("PERSONNAME <", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameLessThanOrEqualTo(String value) {
            addCriterion("PERSONNAME <=", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameLike(String value) {
            addCriterion("PERSONNAME like", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameNotLike(String value) {
            addCriterion("PERSONNAME not like", value, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameIn(List<String> values) {
            addCriterion("PERSONNAME in", values, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameNotIn(List<String> values) {
            addCriterion("PERSONNAME not in", values, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameBetween(String value1, String value2) {
            addCriterion("PERSONNAME between", value1, value2, "personname");
            return (Criteria) this;
        }

        public Criteria andPersonnameNotBetween(String value1, String value2) {
            addCriterion("PERSONNAME not between", value1, value2, "personname");
            return (Criteria) this;
        }

        public Criteria andIdcardnumIsNull() {
            addCriterion("IDCARDNUM is null");
            return (Criteria) this;
        }

        public Criteria andIdcardnumIsNotNull() {
            addCriterion("IDCARDNUM is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardnumEqualTo(String value) {
            addCriterion("IDCARDNUM =", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumNotEqualTo(String value) {
            addCriterion("IDCARDNUM <>", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumGreaterThan(String value) {
            addCriterion("IDCARDNUM >", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumGreaterThanOrEqualTo(String value) {
            addCriterion("IDCARDNUM >=", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumLessThan(String value) {
            addCriterion("IDCARDNUM <", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumLessThanOrEqualTo(String value) {
            addCriterion("IDCARDNUM <=", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumLike(String value) {
            addCriterion("IDCARDNUM like", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumNotLike(String value) {
            addCriterion("IDCARDNUM not like", value, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumIn(List<String> values) {
            addCriterion("IDCARDNUM in", values, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumNotIn(List<String> values) {
            addCriterion("IDCARDNUM not in", values, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumBetween(String value1, String value2) {
            addCriterion("IDCARDNUM between", value1, value2, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andIdcardnumNotBetween(String value1, String value2) {
            addCriterion("IDCARDNUM not between", value1, value2, "idcardnum");
            return (Criteria) this;
        }

        public Criteria andInviteCodeIsNull() {
            addCriterion("INVITE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInviteCodeIsNotNull() {
            addCriterion("INVITE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInviteCodeEqualTo(String value) {
            addCriterion("INVITE_CODE =", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotEqualTo(String value) {
            addCriterion("INVITE_CODE <>", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeGreaterThan(String value) {
            addCriterion("INVITE_CODE >", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INVITE_CODE >=", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeLessThan(String value) {
            addCriterion("INVITE_CODE <", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeLessThanOrEqualTo(String value) {
            addCriterion("INVITE_CODE <=", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeLike(String value) {
            addCriterion("INVITE_CODE like", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotLike(String value) {
            addCriterion("INVITE_CODE not like", value, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeIn(List<String> values) {
            addCriterion("INVITE_CODE in", values, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotIn(List<String> values) {
            addCriterion("INVITE_CODE not in", values, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeBetween(String value1, String value2) {
            addCriterion("INVITE_CODE between", value1, value2, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInviteCodeNotBetween(String value1, String value2) {
            addCriterion("INVITE_CODE not between", value1, value2, "inviteCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeIsNull() {
            addCriterion("INVITED_CODE is null");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeIsNotNull() {
            addCriterion("INVITED_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeEqualTo(String value) {
            addCriterion("INVITED_CODE =", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeNotEqualTo(String value) {
            addCriterion("INVITED_CODE <>", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeGreaterThan(String value) {
            addCriterion("INVITED_CODE >", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeGreaterThanOrEqualTo(String value) {
            addCriterion("INVITED_CODE >=", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeLessThan(String value) {
            addCriterion("INVITED_CODE <", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeLessThanOrEqualTo(String value) {
            addCriterion("INVITED_CODE <=", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeLike(String value) {
            addCriterion("INVITED_CODE like", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeNotLike(String value) {
            addCriterion("INVITED_CODE not like", value, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeIn(List<String> values) {
            addCriterion("INVITED_CODE in", values, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeNotIn(List<String> values) {
            addCriterion("INVITED_CODE not in", values, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeBetween(String value1, String value2) {
            addCriterion("INVITED_CODE between", value1, value2, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andInvitedCodeNotBetween(String value1, String value2) {
            addCriterion("INVITED_CODE not between", value1, value2, "invitedCode");
            return (Criteria) this;
        }

        public Criteria andSourceFlagIsNull() {
            addCriterion("SOURCE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSourceFlagIsNotNull() {
            addCriterion("SOURCE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSourceFlagEqualTo(String value) {
            addCriterion("SOURCE_FLAG =", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotEqualTo(String value) {
            addCriterion("SOURCE_FLAG <>", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagGreaterThan(String value) {
            addCriterion("SOURCE_FLAG >", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_FLAG >=", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagLessThan(String value) {
            addCriterion("SOURCE_FLAG <", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_FLAG <=", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagLike(String value) {
            addCriterion("SOURCE_FLAG like", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotLike(String value) {
            addCriterion("SOURCE_FLAG not like", value, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagIn(List<String> values) {
            addCriterion("SOURCE_FLAG in", values, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotIn(List<String> values) {
            addCriterion("SOURCE_FLAG not in", values, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagBetween(String value1, String value2) {
            addCriterion("SOURCE_FLAG between", value1, value2, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceFlagNotBetween(String value1, String value2) {
            addCriterion("SOURCE_FLAG not between", value1, value2, "sourceFlag");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNull() {
            addCriterion("SOURCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNotNull() {
            addCriterion("SOURCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSourceIdEqualTo(String value) {
            addCriterion("SOURCE_ID =", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotEqualTo(String value) {
            addCriterion("SOURCE_ID <>", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThan(String value) {
            addCriterion("SOURCE_ID >", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_ID >=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThan(String value) {
            addCriterion("SOURCE_ID <", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_ID <=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLike(String value) {
            addCriterion("SOURCE_ID like", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotLike(String value) {
            addCriterion("SOURCE_ID not like", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdIn(List<String> values) {
            addCriterion("SOURCE_ID in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotIn(List<String> values) {
            addCriterion("SOURCE_ID not in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdBetween(String value1, String value2) {
            addCriterion("SOURCE_ID between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotBetween(String value1, String value2) {
            addCriterion("SOURCE_ID not between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagIsNull() {
            addCriterion("FUNCTION_RIGHT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagIsNotNull() {
            addCriterion("FUNCTION_RIGHT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagEqualTo(long value) {
            addCriterion("FUNCTION_RIGHT_FLAG =", value, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagNotEqualTo(long value) {
            addCriterion("FUNCTION_RIGHT_FLAG <>", value, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagGreaterThan(long value) {
            addCriterion("FUNCTION_RIGHT_FLAG >", value, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagGreaterThanOrEqualTo(long value) {
            addCriterion("FUNCTION_RIGHT_FLAG >=", value, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagLessThan(long value) {
            addCriterion("FUNCTION_RIGHT_FLAG <", value, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagLessThanOrEqualTo(long value) {
            addCriterion("FUNCTION_RIGHT_FLAG <=", value, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagIn(List<Long> values) {
            addCriterion("FUNCTION_RIGHT_FLAG in", values, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagNotIn(List<Long> values) {
            addCriterion("FUNCTION_RIGHT_FLAG not in", values, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagBetween(long value1, long value2) {
            addCriterion("FUNCTION_RIGHT_FLAG between", value1, value2, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andFunctionRightFlagNotBetween(long value1, long value2) {
            addCriterion("FUNCTION_RIGHT_FLAG not between", value1, value2, "functionRightFlag");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanIsNull() {
            addCriterion("BUSSINESS_LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanIsNotNull() {
            addCriterion("BUSSINESS_LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanEqualTo(String value) {
            addCriterion("BUSSINESS_LINKMAN =", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanNotEqualTo(String value) {
            addCriterion("BUSSINESS_LINKMAN <>", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanGreaterThan(String value) {
            addCriterion("BUSSINESS_LINKMAN >", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("BUSSINESS_LINKMAN >=", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanLessThan(String value) {
            addCriterion("BUSSINESS_LINKMAN <", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanLessThanOrEqualTo(String value) {
            addCriterion("BUSSINESS_LINKMAN <=", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanLike(String value) {
            addCriterion("BUSSINESS_LINKMAN like", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanNotLike(String value) {
            addCriterion("BUSSINESS_LINKMAN not like", value, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanIn(List<String> values) {
            addCriterion("BUSSINESS_LINKMAN in", values, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanNotIn(List<String> values) {
            addCriterion("BUSSINESS_LINKMAN not in", values, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanBetween(String value1, String value2) {
            addCriterion("BUSSINESS_LINKMAN between", value1, value2, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessLinkmanNotBetween(String value1, String value2) {
            addCriterion("BUSSINESS_LINKMAN not between", value1, value2, "bussinessLinkman");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneIsNull() {
            addCriterion("BUSSINESS_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneIsNotNull() {
            addCriterion("BUSSINESS_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneEqualTo(String value) {
            addCriterion("BUSSINESS_PHONE =", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneNotEqualTo(String value) {
            addCriterion("BUSSINESS_PHONE <>", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneGreaterThan(String value) {
            addCriterion("BUSSINESS_PHONE >", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("BUSSINESS_PHONE >=", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneLessThan(String value) {
            addCriterion("BUSSINESS_PHONE <", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneLessThanOrEqualTo(String value) {
            addCriterion("BUSSINESS_PHONE <=", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneLike(String value) {
            addCriterion("BUSSINESS_PHONE like", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneNotLike(String value) {
            addCriterion("BUSSINESS_PHONE not like", value, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneIn(List<String> values) {
            addCriterion("BUSSINESS_PHONE in", values, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneNotIn(List<String> values) {
            addCriterion("BUSSINESS_PHONE not in", values, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneBetween(String value1, String value2) {
            addCriterion("BUSSINESS_PHONE between", value1, value2, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andBussinessPhoneNotBetween(String value1, String value2) {
            addCriterion("BUSSINESS_PHONE not between", value1, value2, "bussinessPhone");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeIsNull() {
            addCriterion("ASSOCIATED_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeIsNotNull() {
            addCriterion("ASSOCIATED_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeEqualTo(String value) {
            addCriterion("ASSOCIATED_CODE =", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeNotEqualTo(String value) {
            addCriterion("ASSOCIATED_CODE <>", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeGreaterThan(String value) {
            addCriterion("ASSOCIATED_CODE >", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ASSOCIATED_CODE >=", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeLessThan(String value) {
            addCriterion("ASSOCIATED_CODE <", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeLessThanOrEqualTo(String value) {
            addCriterion("ASSOCIATED_CODE <=", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeLike(String value) {
            addCriterion("ASSOCIATED_CODE like", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeNotLike(String value) {
            addCriterion("ASSOCIATED_CODE not like", value, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeIn(List<String> values) {
            addCriterion("ASSOCIATED_CODE in", values, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeNotIn(List<String> values) {
            addCriterion("ASSOCIATED_CODE not in", values, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeBetween(String value1, String value2) {
            addCriterion("ASSOCIATED_CODE between", value1, value2, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andAssociatedCodeNotBetween(String value1, String value2) {
            addCriterion("ASSOCIATED_CODE not between", value1, value2, "associatedCode");
            return (Criteria) this;
        }

        public Criteria andPhoto4IsNull() {
            addCriterion("PHOTO4 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto4IsNotNull() {
            addCriterion("PHOTO4 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto4EqualTo(String value) {
            addCriterion("PHOTO4 =", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotEqualTo(String value) {
            addCriterion("PHOTO4 <>", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4GreaterThan(String value) {
            addCriterion("PHOTO4 >", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4GreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO4 >=", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4LessThan(String value) {
            addCriterion("PHOTO4 <", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4LessThanOrEqualTo(String value) {
            addCriterion("PHOTO4 <=", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4Like(String value) {
            addCriterion("PHOTO4 like", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotLike(String value) {
            addCriterion("PHOTO4 not like", value, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4In(List<String> values) {
            addCriterion("PHOTO4 in", values, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotIn(List<String> values) {
            addCriterion("PHOTO4 not in", values, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4Between(String value1, String value2) {
            addCriterion("PHOTO4 between", value1, value2, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto4NotBetween(String value1, String value2) {
            addCriterion("PHOTO4 not between", value1, value2, "photo4");
            return (Criteria) this;
        }

        public Criteria andPhoto5IsNull() {
            addCriterion("PHOTO5 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto5IsNotNull() {
            addCriterion("PHOTO5 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto5EqualTo(String value) {
            addCriterion("PHOTO5 =", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotEqualTo(String value) {
            addCriterion("PHOTO5 <>", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5GreaterThan(String value) {
            addCriterion("PHOTO5 >", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5GreaterThanOrEqualTo(String value) {
            addCriterion("PHOTO5 >=", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5LessThan(String value) {
            addCriterion("PHOTO5 <", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5LessThanOrEqualTo(String value) {
            addCriterion("PHOTO5 <=", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5Like(String value) {
            addCriterion("PHOTO5 like", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotLike(String value) {
            addCriterion("PHOTO5 not like", value, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5In(List<String> values) {
            addCriterion("PHOTO5 in", values, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotIn(List<String> values) {
            addCriterion("PHOTO5 not in", values, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5Between(String value1, String value2) {
            addCriterion("PHOTO5 between", value1, value2, "photo5");
            return (Criteria) this;
        }

        public Criteria andPhoto5NotBetween(String value1, String value2) {
            addCriterion("PHOTO5 not between", value1, value2, "photo5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PJ_ASSOCIATOR
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}